### PR TITLE
Feature/stop connection

### PR DESCRIPTION
**Pull request by nivrith**
Add Ability to Stop Connection
Add hook to modify connection properties before start (eg, qs, auth token etc) 
Minor Cleanup and fixes

TODO: update docs

### CODE REVIEW

**Comment by Odonno** [comment]
Hi @nivrith 

First, thank you for contributing on this package.
I can see that your PR contains 2 features: 

* stop a signalr connection / hub
* add a `beforeConnectionStart` function to the hub

I believe that should be splitted in 2 PRs but until then I have some questions.

* I didn't think about the `stop` feature and this is a brilliant idea. You made a stop function and a rxjs Subject, but how do you stop a hub? I think you'd need an action and an effect to that. What do you think?
* Regarding the `beforeConnectionStart` function, I see that you want to mutate the hub before the connection start. But I do not understand why clearly, can you explain it to me? For your information, you can pass the hub `options` in the `startSignalrHub` action, options that can be access token or connection mode, etc..

**Comment by nivrith** [comment]
Hi @Odonno, 

Thanks for your prompt reply. yes I agree that we should split it into two separate PRs . Sorry about that , actually a Product of my office uses this package as a dependency and there were some things that we needed for our use case so we forked the repo as we needed the modifications immediately. But I am happy to split these features into two PRs and we could close/cancel this one. Also here is my response to your other questions:

- Absolutely , actually I did make action and effects but I think that is still on the fork . Apologies for the mix up , was on a time constraint. Will take care of that in the split PR

- And regarding the `beforeConnectionStart` function, the reason we needed this was to attach our authToken before connecting to the connection object. I did think of passing this in the signalR Options initially but it turned out that the qs property actually exists on the connection object and we needed to pass in a new authToken on each time connection would start

**Comment by Odonno** [comment]
Alright.

For the stop feature, let me know when you're done.

About the `beforeConnectionStart` function, I am a bit confused because I work with both the SignalR for .NET Framework and SignalR for .NET Core. And it seems there are more differences that I imagine in the first place. 
In SignalR for .NET Core, you can pass an auth token function, the transport modes & co. But in .NET Framework, I am not sure what you can do. It seems we can't have the same process, I need to figure it out.

Thanks for your help anyway.

**Comment by nivrith** [comment]
I have sent the PR for stop connection feature in #3 . I am closing this PR now

Yes. I tried to find a way to add authToken to query string in options but there didn't seem to be a way unless we had access to the connection object, that's why I then went down the path of the `beforeConnectionStart` hook. I may be missing something, if you figure a cleaner way to do this, would be great ! 

Thanks,
Nivrith

**Comment by Odonno** [comment]
Regarding the `beforeConnectionStart` hook, I just looked at the code and tried to find the differences between the .NET Core and .NET Framework versions of SignalR. They are huge because a lot of properties are stored in the connection object. It's something I did not know about and I had no usage of it but it is clearly important to let developers update this part, like the query string you mentioned.

Here is the definition of the connection object: 

```ts
interface Connection {
    clientProtocol: string;
    ajaxDataType: string;
    contentType: string;
    id: string;
    json: JSON;
    logging: boolean;
    url: string;
    qs: string | Object;
    state: number;
    reconnectDelay: number;
    transportConnectTimeout: number;
    /**
    * This should be set by the server in response to the negotiate request (30s default)
    */
    disconnectTimeout: number;
    /**
    * This should be set by the server in response to the negotiate request
    */
    reconnectWindow: number;
    /**
    * Warn user of slow connection if we breach the X% mark of the keep alive timeout
    */
    keepAliveWarnAt: number;

    hub: Hub.Connection;

    lastError: ConnectionError;
    resources: Resources;
}
```

I removed the functions from the definition and I can see there is also property you don't want to update, like the hub. So, I propose to create a new type definition:

```ts
export type SignalRAdditionalConnectionOptions = {
    qs: string | Object;
    reconnectDelay: number;
    transportConnectTimeout: number;
};
```

And so will get more control over the the hub when starting it without polluting the store.

```ts
export const startSignalRHub = createAction(
    '@ngrx/signalr/startHub',
    props<{ 
        hubName: string, 
        url?: string | undefined, 
        options?: SignalR.ConnectionOptions | undefined,
        additionalOptions?: SignalRAdditionalConnectionOptions | undefined
    }>()
);
```

And then updating the `connection` inside the `startHub` function will be really easy. 
What do you think? If you have any question, please go ahead.

**Pull request closed without merging**
